/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Book;
import Service.AdminService;
import java.awt.Color;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class AddBookFrame extends javax.swing.JFrame {
    AdminService adminService;
    Book book;
    /**
     * Creates new form AddBookFrame
     */
    public AddBookFrame() {
        initComponents();
        adminService = new AdminService();
        book = new Book();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bookNameTextField = new javax.swing.JTextField();
        authorLabel = new javax.swing.JLabel();
        genraLabel = new javax.swing.JLabel();
        requireLabel4 = new javax.swing.JLabel();
        authorTextField = new javax.swing.JTextField();
        requireLabel5 = new javax.swing.JLabel();
        genreComboBox = new javax.swing.JComboBox<>();
        DescriptionLabel = new javax.swing.JLabel();
        availabilityTextField = new javax.swing.JTextField();
        requireLabel1 = new javax.swing.JLabel();
        publicYearTextField = new javax.swing.JTextField();
        publicYearLabel = new javax.swing.JLabel();
        requireLabel2 = new javax.swing.JLabel();
        addNewBookButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        availabilityLabel = new javax.swing.JLabel();
        bookNameLabel = new javax.swing.JLabel();
        requireLabel6 = new javax.swing.JLabel();
        requireLabel3 = new javax.swing.JLabel();
        warningLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addNewBookTitleLabel = new javax.swing.JLabel();

        setTitle("Add Book Frame");

        jPanel1.setBackground(new java.awt.Color(244, 244, 244));

        bookNameTextField.setBackground(new java.awt.Color(255, 156, 192));
        bookNameTextField.setForeground(new java.awt.Color(0, 0, 0));
        bookNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookNameTextFieldActionPerformed(evt);
            }
        });

        authorLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        authorLabel.setForeground(new java.awt.Color(0, 0, 0));
        authorLabel.setText("Author:");

        genraLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genraLabel.setForeground(new java.awt.Color(0, 0, 0));
        genraLabel.setText("Genre:");

        requireLabel4.setForeground(new java.awt.Color(255, 0, 0));
        requireLabel4.setText("(*)");

        authorTextField.setBackground(new java.awt.Color(255, 156, 192));
        authorTextField.setForeground(new java.awt.Color(0, 0, 0));

        requireLabel5.setForeground(new java.awt.Color(255, 0, 0));
        requireLabel5.setText("(*)");

        genreComboBox.setBackground(new java.awt.Color(157, 0, 57));
        genreComboBox.setForeground(new java.awt.Color(255, 255, 255));
        genreComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Null", "Science", "Fiction", "Comedy", " " }));

        DescriptionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DescriptionLabel.setForeground(new java.awt.Color(0, 0, 0));
        DescriptionLabel.setText("Description");

        availabilityTextField.setBackground(new java.awt.Color(255, 156, 192));
        availabilityTextField.setForeground(new java.awt.Color(0, 0, 0));

        requireLabel1.setForeground(new java.awt.Color(255, 0, 0));
        requireLabel1.setText("(*)");

        publicYearTextField.setBackground(new java.awt.Color(255, 156, 192));
        publicYearTextField.setForeground(new java.awt.Color(0, 0, 0));

        publicYearLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        publicYearLabel.setForeground(new java.awt.Color(0, 0, 0));
        publicYearLabel.setText("Public year:");

        requireLabel2.setForeground(new java.awt.Color(255, 0, 0));
        requireLabel2.setText("(*)");

        addNewBookButton.setBackground(new java.awt.Color(157, 0, 57));
        addNewBookButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addNewBookButton.setForeground(new java.awt.Color(255, 255, 255));
        addNewBookButton.setText("Add");
        addNewBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewBookButtonActionPerformed(evt);
            }
        });

        descriptionTextArea.setBackground(new java.awt.Color(255, 156, 192));
        descriptionTextArea.setColumns(20);
        descriptionTextArea.setForeground(new java.awt.Color(0, 0, 0));
        descriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(descriptionTextArea);

        availabilityLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        availabilityLabel.setForeground(new java.awt.Color(0, 0, 0));
        availabilityLabel.setText("Availability:");

        bookNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bookNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        bookNameLabel.setText("Book Name:");

        requireLabel6.setForeground(new java.awt.Color(255, 0, 0));
        requireLabel6.setText("(*)");

        requireLabel3.setForeground(new java.awt.Color(255, 0, 0));
        requireLabel3.setText("(*)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(requireLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(requireLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(requireLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(requireLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(requireLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(requireLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bookNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(bookNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(authorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DescriptionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(genraLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(genreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(publicYearLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(publicYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(availabilityLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(availabilityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(addNewBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(256, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookNameLabel)
                    .addComponent(requireLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorLabel)
                    .addComponent(requireLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DescriptionLabel)
                        .addComponent(requireLabel3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genraLabel)
                    .addComponent(requireLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(publicYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(publicYearLabel)
                    .addComponent(requireLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(requireLabel5)
                        .addComponent(availabilityLabel))
                    .addComponent(availabilityTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(327, Short.MAX_VALUE)
                    .addComponent(addNewBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel2.setBackground(new java.awt.Color(157, 0, 57));

        addNewBookTitleLabel.setBackground(new java.awt.Color(157, 0, 57));
        addNewBookTitleLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        addNewBookTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        addNewBookTitleLabel.setText("NEW BOOK");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(addNewBookTitleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addNewBookTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addNewBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewBookButtonActionPerformed
        // TODO add your handling code here:
        if(bookNameTextField.getText().isEmpty()
            || authorTextField.getText().isEmpty()
            || descriptionTextArea.getText().isEmpty()
            || genreComboBox.getSelectedItem().equals("Null")
            || publicYearTextField.getText().isEmpty()
            || availabilityTextField.getText().isEmpty()) {

            warningLabel.setText("Enter the (*) requirement");
            warningLabel.setForeground(Color.red);

        } else if (Integer.parseInt(publicYearTextField.getText()) <= 0){
            JOptionPane.showMessageDialog(null,
                    "Year Public of book cannot be zero or negative!",
                    "Warning",
                    JOptionPane.WARNING_MESSAGE);
            publicYearTextField.setText("");
        } else if (Integer.parseInt(availabilityTextField.getText()) < 0) {
            JOptionPane.showMessageDialog(null,
                    "Quantity of book cannot be negative!",
                    "Warning",
                    JOptionPane.WARNING_MESSAGE);
            availabilityTextField.setText("");
        } else if (Integer.parseInt(publicYearTextField.getText()) <= 0 
                   && Integer.parseInt(availabilityTextField.getText()) < 0){
                
            JOptionPane.showMessageDialog(null,
                    "Public Year and Quantity cannot be negative!",
                    "Warning",
                    JOptionPane.WARNING_MESSAGE);   
        } else {
            String name = bookNameTextField.getText();
            String author = authorTextField.getText();
            String description = descriptionTextArea.getText();
            String genre = null;
            if(genreComboBox.getSelectedItem().equals("Science")) {
                genre = "Science";
            } else if(genreComboBox.getSelectedItem().equals("Fiction")) {
                genre = "Fiction";
                
            } else if(genreComboBox.getSelectedItem().equals("Fiction")) {
                genre = "Fiction";
                
            }
            String publicYear = publicYearTextField.getText();
            int availability = parseInt(availabilityTextField.getText());

            book.setBookName(name);
            book.setBookAuthor(author);
            book.setBookDescription(description);
            book.setBookGerne(genre);
            book.setYearPublic(publicYear);
            book.setAvailability(availability);

            String ConfirmationMessage = "Do you want to add this new book: \n"
            + "Name: " + name + "\n"
            + "Author: " + author + "\n"
            + "Description: " + description + "\n"
            + "Genre: " + genre + "\n"
            + "Public year:" + publicYear + "\n"
            + "Availability: " + availability + "\n";

            int result = JOptionPane.showConfirmDialog(null,
                ConfirmationMessage,
                "NEW BOOK CONFIRMATION",
                JOptionPane.YES_NO_OPTION);

            if (result == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(null,
                    "Add Book Success!",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
                adminService.addBook(book);
            }

        }
    }//GEN-LAST:event_addNewBookButtonActionPerformed

    private void bookNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookNameTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JButton addNewBookButton;
    private javax.swing.JLabel addNewBookTitleLabel;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JTextField authorTextField;
    private javax.swing.JLabel availabilityLabel;
    private javax.swing.JTextField availabilityTextField;
    private javax.swing.JLabel bookNameLabel;
    private javax.swing.JTextField bookNameTextField;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JLabel genraLabel;
    private javax.swing.JComboBox<String> genreComboBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel publicYearLabel;
    private javax.swing.JTextField publicYearTextField;
    private javax.swing.JLabel requireLabel1;
    private javax.swing.JLabel requireLabel2;
    private javax.swing.JLabel requireLabel3;
    private javax.swing.JLabel requireLabel4;
    private javax.swing.JLabel requireLabel5;
    private javax.swing.JLabel requireLabel6;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
